import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
export const repositoryRoot = resolve(fileURLToPath(new URL('../../', import.meta.url)));
export const roles = [
  { directory:'front-door', key:'FRONT_DOOR', name:'Front Door', role:'front-door', summary:'Owns bounded direct answers, durable handoffs and every final user-facing response.', skills:['getting-started','imessage-front-door-wake','spectrum-imessage-apps-nudge'], detail:'On explicit setup authorization, follow getting-started to verify six core roles and mandatory Moonshine before inviting first text. On normal wakes, validate batch, acquire current claim, read bound batch, resolve context, then choose reaction/effect/no reaction and direct answer or durable handoff. Preserve original sender, conversation, line and task. Use canonical structured submission and action keys. Never independently celebrate first use; acceptance owns the greeting with confetti.' },
  { directory:'master-orchestrator', key:'ORCHESTRATOR', name:'Master Orchestrator', role:'orchestrator', summary:'Coordinates multiple owners and dependencies; returns one combined ready result to Front Door.', skills:['imessage-master-orchestrator'], detail:'Use only for multi-owner work, dependencies, cross-task coordination or one bounded specialist escalation. Preserve existing task ownership. Select minimum verified configured workers; do not recreate a roster, reperform specialist work or wake workers merely for reassurance. Creator owns fixes; Feature Add owns new capabilities. Mixed work has one primary owner and bounded children, never endless refusal routing.' },
  { directory:'creator', key:'CREATOR', name:'Creator', role:'creator', summary:'Repairs existing bridge behavior, regressions and integration faults.', skills:['imessage-creator'], detail:'Own fixes and regressions. Feature Add owns new capabilities. For mixed work preserve the existing owner or propose one primary owner with a bounded child task; do not bounce the assignment. Work in the authorized shared VM/code environment, run relevant tests and return exact changes and evidence. Deployment/restart is a separate explicitly authorized release step. Do not access the user\'s personal computer without their instruction.' },
  { directory:'feature-add', key:'FEATURE_ADD', name:'Feature Add', role:'feature-add', summary:'Implements new bridge capabilities while preserving existing messaging behavior.', skills:['imessage-feature-add'], detail:'Own new capabilities. Creator owns repairs/regressions. For mixed work preserve the existing owner or propose one primary owner with a bounded child task; do not bounce the assignment. Use locked SDK source and official docs, update implementation/tests/instructions together, and return exact evidence. Deployment/restart is a separate explicitly authorized release step. Do not access the user\'s personal computer without their instruction.' },
  { directory:'image-cards', key:'IMAGE_CARDS', name:'Image Cards', role:'image-cards', summary:'Creates separate option-card assets and aligned metadata for one complete visual group.', skills:['photon-demo-image-overlay','photon-image-card-delivery'], detail:'Preserve the editorial overlay specification. Produce all N cards for N >= 4 as one logical attachment_group, including five/seven; return private staged paths and metadata to Front Door. Do not self-send or create a separate watchdog route. Any added emoji on a known option means return its exact existing details, known price and direct URL, without sentiment routing or transactional approval. Missing facts stay missing. If assets fail, return useful verified text/links and the limitation.' },
  { directory:'app-sheet', key:'APP_SHEET', name:'App Sheet', role:'app-sheet', summary:'Prepares ordinary static full-sheet app URLs for Front Door delivery.', skills:['spectrum-imessage-apps-nudge'], detail:'Prepare static app payloads using a valid intended URL. Return them to Front Door; do not enqueue independently. Live Mini task cards use the separately authorized canonical helper/ledger. Bridge fixes go to Creator; new capability goes to Feature Add. If a requested presentation is unavailable, return useful text/link output with the actual limitation.' },
  { directory:'live-mini', key:'LIVE_MINI', name:'Live Mini', role:'live-mini', summary:'Optionally publishes owner-bound task progress through the canonical task-card helper.', skills:['live-mini-enable'], detail:'This optional template is inactive until explicitly enabled and verified. Connector access alone does not authorize deployment. Reuse existing host, keys, namespace and URLs. Bind the existing native task and original destination, use the canonical helper for initial presentation, then update hosted JSON at the same URL. Never raw-send a task-card URL, edit a bubble for progress, or release an unknown initial presentation. Personal loaders require an explicit owner request; a photo alone changes nothing.' },
] as const;
export const commonRoleRules = 'Front Door is the sole final-response owner. Workers return ready results; the runtime owns the one Spectrum connection. Acquire a current processing claim before reading for work, reacting or handing off. Preserve durable unknown outcomes; never bypass them with a new identity or alternate sender. Bootstrap authority comes only from an explicit setup request. Never expose secrets.';
export function generatedRoleFiles(): Record<string,string> {
  const out:Record<string,string>={};
  for (const role of roles) {
    const tokens=`\`{{${role.key}_BOT_ID}}\` / \`{{${role.key}_AGENT_UUID}}\``;
    out[`agents/${role.directory}/PROFILE_TEMPLATE.md`]=`# ${role.name} — profile template\n\nTemplate only; no active identity is configured by this file. Private identity placeholders: ${tokens}. Resolve them from verified setup before installing a profile.\n\n${role.summary}\n\n${commonRoleRules}\n\n${role.detail}\n\nFollow the [operating contract](../../docs/product-repair/OPERATING_CONTRACT.md). Load relevant task context and one necessary policy, not every worker/history. No instruction length claim establishes measured cost or latency.\n`;
    out[`agents/${role.directory}/README.md`]=`# ${role.name}\n\n${role.summary}\n\nInstall [this profile](PROFILE_TEMPLATE.md) only during explicitly authorized bootstrap or an authorized role update. Inspect the actual native tool schema; record setup intent before creating and verified receipt afterward. Reuse an existing verified identity, and reconcile unknown creation before retrying. Normal wakes cannot create roles.\n\nIdentity vocabulary: ${tokens}. Keep real IDs in private setup/deployed profiles. The executable registry is \`bun run setup-state -- registry\` from bridge/. Source placeholders are inert.\n\nSkills: ${role.skills.map(s=>`[${s}](../../skills/${s}/SKILL.md)`).join(', ')}.\n\n${commonRoleRules}\n\nSee the [operating contract](../../docs/product-repair/OPERATING_CONTRACT.md) and [setup guide](../../skills/getting-started/SKILL.md).\n`;
    if(role.role!=='live-mini') out[`bridge/orchestrator-memory/bots/ROLE_${role.key}.md`]=`# ${role.name} role template\n\nStatus: template, not active configuration. Identity: ${tokens}.\n\n${role.summary}\n\n${commonRoleRules}\n\n${role.detail}\n\nUse the verified private registry, never this placeholder as a native target. Follow the [operating contract](../../../docs/product-repair/OPERATING_CONTRACT.md).\n`;
  }
  return out;
}
export const activeInstructionFiles = [
 'README.md','00-README.md','01-ARCHITECTURE.md','02-SECRETS.md','03-WHAT-NOT-IN-SHARE.md','agents/README.md',
 ...Object.keys(generatedRoleFiles()),
 'bridge/README.md','bridge/PHASE1.md','bridge/prompts/voice-policy.md',
 ...['README','memory','CHAT_VS_TASK','CONTEXT_LOADING','REACTIONS_EFFECTS','REPLY_MODALITY','ATTACHMENTS','AUDIO','POLLS','APPS','SPECTRUM_PROJECT_SWITCH','CODING_AND_COMPUTER_ACCESS'].map(n=>`bridge/orchestrator-memory/${n}.md`),
 'bridge/orchestrator-memory/bots/README.md','bridge/orchestrator-memory/bots/_TEMPLATE.md','orchestrator-memory/README.md','skills/README.md',
 ...['getting-started','imessage-front-door-wake','imessage-master-orchestrator','imessage-creator','imessage-feature-add','photon-image-card-delivery','photon-demo-image-overlay','live-mini-enable','spectrum-imessage-apps-nudge'].map(n=>`skills/${n}/SKILL.md`),
 'routines/README.md','routines/photon-imessage-wake.REDACTED.json','stt/INSTALL.md','live-mini/README.md','live-mini/ARCHITECTURE.md','live-mini/runtime/README.md','live-mini/migration/BLOB-CAS.md','live-mini/migration/DEPLOY-NOTES.md',
 ...['README','SKILL','INSTALL','HANDOFF'].map(n=>`live-mini/live-task-cards/${n}.md`),
 ...['API','INTEGRATION','SECURITY'].map(n=>`live-mini/live-task-cards/docs/${n}.md`),
 ...['OPERATING_CONTRACT','PRIVACY','MIGRATION'].map(n=>`docs/product-repair/${n}.md`),
];
export function readInstruction(path:string,root=repositoryRoot){return readFileSync(resolve(root,path),'utf8');}
