import { createHash } from 'node:crypto';
import { existsSync, lstatSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { repositoryRoot } from './instruction-catalog.ts';
const hostPrefix = 'live-mini/live-task-cards/';
const hostManifest = hostPrefix + 'MANIFEST.sha256.json';
export function manifestContents(root = repositoryRoot) {
  const git = Bun.spawnSync(['git', '-C', root, 'ls-files', '--cached', '--others', '--exclude-standard', '-z']);
  if (git.exitCode !== 0) throw new Error('MANIFEST_GIT_FAILED');
  const files = [...new Set(git.stdout.toString().split('\0').filter(Boolean))].filter(path => existsSync(resolve(root, path)) && path !== 'MANIFEST.txt' && path !== hostManifest).sort();
  for (const path of files) {
    if (/^(?:bridge\/data|live-mini\/runtime\/state|live-mini\/secrets)\/(?!\.gitkeep$)/.test(path) || /(?:^|\/)\.env(?!\.example$)/.test(path) || /(?:^|\/)node_modules\//.test(path)) throw new Error('MANIFEST_PRIVATE_PATH_REJECTED');
    if (!lstatSync(resolve(root, path)).isFile()) throw new Error('MANIFEST_NON_FILE_REJECTED');
  }
  const digest = (path: string) => createHash('sha256').update(readFileSync(resolve(root, path))).digest('hex');
  const host = JSON.stringify(Object.fromEntries(files.filter(path => path.startsWith(hostPrefix) && !/\.(?:tar\.gz|zip)(?:\.sha256)?$/.test(path)).map(path => [path.slice(hostPrefix.length), digest(path)])), null, 2) + '\n';
  const entries = files.map(path => [path, digest(path)]);
  entries.push([hostManifest, createHash('sha256').update(host).digest('hex')]);
  const inventory = '# SHA-256 source inventory; generated by bridge/scripts/refresh-manifests.ts\n# Excludes this manifest, ignored private/runtime/build files, and absent tracked files.\n' + entries.sort(([a], [b]) => a!.localeCompare(b!, 'en')).map(([path, hash]) => `${hash}  ${path}`).join('\n') + '\n';
  return { host, inventory, fileCount: entries.length };
}
export function refreshManifests(check = false, root = repositoryRoot) {
  const { host, inventory, fileCount } = manifestContents(root);
  if (check) {
    if (readFileSync(resolve(root, hostManifest), 'utf8') !== host || readFileSync(resolve(root, 'MANIFEST.txt'), 'utf8') !== inventory) throw new Error('MANIFEST_DRIFT');
  } else {
    writeFileSync(resolve(root, hostManifest), host);
    writeFileSync(resolve(root, 'MANIFEST.txt'), inventory);
  }
  return { files: fileCount, checked: check };
}
if (import.meta.main) {
  if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('MANIFEST_ARGUMENT_INVALID');
  console.log(JSON.stringify(refreshManifests(process.argv.includes('--check'))));
}
