import { test, expect } from "bun:test";
import { unlinkSync, writeFileSync } from "node:fs";
import { deliveryFixture } from "./delivery-fixture.ts";
import { assetsAreComplete, cardsActionKey, writeCardsReadyMarker, findReadyImageStacks, finalEnqueueReadyStack, drainCardsReady, outboundAlreadyCoversBatch, type CardsReadyMarker } from "./cards-ready.ts";
function marker(f:ReturnType<typeof deliveryFixture>, count=5):CardsReadyMarker { const paths=Array.from({length:count},()=>f.asset());return{submission:f.submission({kind:"attachment_group",spaceId:f.destination.spaceId,batchId:f.batch.batchId,attachmentPaths:paths,cards:paths.map((_,i)=>({optionId:`option-${i}`,title:`Choice ${i}`,details:`Details ${i}`}))},cardsActionKey(f.batch.batchId,"v1")),expectedCount:count,revision:"v1",readyAt:new Date().toISOString()}; }

test("K01 concurrent Front Door/watchdog inserts one logical grouped operation",async()=>{const f=deliveryFixture();try{const m=marker(f);writeCardsReadyMarker(m,f.store);const [front]=await Promise.all([finalEnqueueReadyStack(m,f),drainCardsReady(f)]);expect(front.outboundIds).toHaveLength(1);expect(f.store.listOutbound()).toHaveLength(1);expect(await findReadyImageStacks(f)).toHaveLength(0);expect(f.store.operationStatus(f.destination,"final",m.submission.actionKey)[0]!.id).toBe(front.outboundIds[0]!);}finally{f.cleanup();}});

test("K02 exact operation states never equated to delivered by filenames",async()=>{for(const state of ["unknown","failed"] as const){const f=deliveryFixture();try{const m=marker(f);const result=await finalEnqueueReadyStack(m,f);expect(outboundAlreadyCoversBatch(f.store,f.destination,f.batch.batchId,"v1")[0]!.state).toBe("queued");const claimed=f.store.claimOutbound()!;f.store.settleOutbound(claimed.item.id,claimed.attemptId,{state,code:"test-evidence"});writeCardsReadyMarker(m,f.store);await drainCardsReady(f);expect(f.store.listOutbound()).toHaveLength(1);expect(outboundAlreadyCoversBatch(f.store,f.destination,f.batch.batchId,"v1")[0]!.state).toBe(state);expect(outboundAlreadyCoversBatch(f.store,f.destination,f.batch.batchId,"v2")).toEqual([]);}finally{f.cleanup();}}});

test("K03 missing middle card waits without shifting metadata; complete five remains group",async()=>{const f=deliveryFixture();try{const m=marker(f);if(m.submission.payload.kind!=="attachment_group")throw new Error("fixture");const middle=m.submission.payload.attachmentPaths[2]!;unlinkSync(middle);writeCardsReadyMarker(m,f.store);expect(await findReadyImageStacks(f)).toHaveLength(0);expect(await drainCardsReady(f)).toBe(0);expect(f.store.listOutbound()).toHaveLength(0);writeFileSync(middle,Buffer.from([255,216,0,255,217]),{mode:0o600});expect(await drainCardsReady(f)).toBe(1);const item=f.store.listOutbound()[0]!;expect(item.kind).toBe("attachment_group");if(item.kind==="attachment_group"){expect(item.attachmentPaths).toHaveLength(5);expect(item.cards?.[2]?.title).toBe("Choice 2");}}finally{f.cleanup();}});

test("card metadata/count conflicts fail closed; stability helper requires exact expected count",async()=>{const f=deliveryFixture();try{const m=marker(f);expect(()=>writeCardsReadyMarker({...m,expectedCount:4},f.store)).toThrow("CARD_ALIGNMENT_INVALID");expect(()=>writeCardsReadyMarker({...m,submission:{...m.submission,actionKey:"random"}},f.store)).toThrow("CARD_CONTEXT_INVALID");expect(assetsAreComplete({paths:["a","b","c","d"],expectedCount:5,newestMtimeMs:1,nowMs:20000})).toBe(false);expect(assetsAreComplete({paths:["a","b","c","d"],expectedCount:4,newestMtimeMs:1,nowMs:20000})).toBe(true);}finally{f.cleanup();}});

test("historical completed markers do not block pending kind enumeration",async()=>{const f=deliveryFixture();try{for(let i=0;i<1005;i++)f.store.setMetadata("cards-ready-completed",String(i),{done:true});const m=marker(f);writeCardsReadyMarker(m,f.store);expect(await drainCardsReady(f)).toBe(1);expect(f.store.listMetadata("cards-ready-pending")).toEqual([]);}finally{f.cleanup();}});
